name: Deploy on Push

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build (replace with your build command)
        run: npm install # Example build command for a Node.js project

      - name: Deploy to staging (replace with your deployment command)
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist  # Replace with your build output directory
